config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :customers
  resources :projects
  resources :tasks
  resources :task_logs, only: [:create, :new]
  root to: 'customers#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :projects
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks
  belongs_to :customer
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :task_logs
  belongs_to :project
end

app/models/task_log.rb
class TaskLog < ApplicationRecord
  belongs_to :task
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :rememberable
          :validatable

  has_many :task_logs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_customer, except: [:index, :new, :create]

  def index
    @customers = Customer.all
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.create(customer_params)

    redirect_to @customer, notice: 'Created Successfully'
  end

  def show
  end

  def update
    if @customer.update(customer_params)
      redirect_to @customer, notice: 'Updated Successfully'
    else
      redirect_to :root, error: 'Could not update customer.'
    end
  end

  def destroy
    @customer.destroy!

    redirect_to :root, notice: "Deleted Successfully."
  end

  private

  def customer_params
    params.require(:customer).permit(:name)
  end

  def find_customer
    @customer = Customer.find(params[:id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_project, except: [:index, :new, :create]

  def index
    @projects = Project.all
  end

  def show
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.create(project_params)

    redirect_to @project, notice: 'Created Successfully'
  end

  def update
    @project.update(project_params)

    redirect_to @project, notice: 'Updated Successfully'
  end

  def destroy
    @project.destroy!

    redirect_to :root, notice: "Deleted Successfully."
  end

  private

  def project_params
    params.required(:project).permit(:name, :customer_id)
  end

  def find_project
    @project = Project.find(params[:id])
  end

end

app/controllers/task_logs_controller.rb
class TaskLogsController < ApplicationController
  before_action :authenticate_user!

  def new
    @task_log = TaskLog.new
  end

  def create
    @task_log = TaskLog.create(task_log_params)

    redirect_to tasks_path, notice: 'Time logged Successfully'
  end

  private

  def task_log_params
    params.required(:task_log).permit(:duration_minutes, :project_id, :user_id)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :find_task, except: [:index, :new, :create]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)

    redirect_to @task, notice: 'Created Successfully'
  end

  def update
    @task.update(task_params)

    redirect_to @task, notice: 'Updated Successfully'
  end

  def destroy
    @task.destroy!

    redirect_to :root, notice: "Deleted Successfully."
  end

  private

  def task_params
    params.required(:task).permit(:description, :project_id)
  end

  def find_task
    @task = Task.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/customers/_form.html.erb
<%= simple_form_for @customer do |f| %>
  <%= f.input :name %>
  <%= f.button :submit %>
<% end %>

app/views/customers/edit.html.erb
<h1>Create Customer</h1>
<%= render partial: 'form' %>

app/views/customers/index.html.erb
<h2>Customers</h2>

<div class="button-container">
  <% @customers.each do |customer| %>
    <div class="m-top">
      <%= link_to customer do %>
        Customer: <%= customer.name %>
      <% end %>
    </div>
  <% end %>
</div>

<div>
  <%= link_to 'Create a customer', new_customer_path %>
</div>

app/views/customers/new.html.erb
<h1>New Customer</h1>
<%= render partial: 'form' %>

app/views/customers/show.html.erb
<h3> Customer #<%= @customer.id %> </h3>

<div>
  Name: <%= @customer.name %>
  <br>
  Created at <%= @customer.created_at.strftime('%m/%d/%Y @ %I:%M%p') %>
</div>

<div class="button-container">
  <%= link_to "Edit", edit_customer_path %>
  <%= link_to "Delete", customer_path, method: :delete, data: { confirm: 'Are you sure?' } %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrackTasker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'main', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="links">
      <%= link_to 'Customers', customers_path %>
      <%= link_to 'Projects', projects_path %>
      <%= link_to 'Tasks', tasks_path %>
    </div>
    <div class="notifications">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
    <div id="main" class="card">
      <%= yield %>
    </div>
    <div id="footer">
    </div>
  </body>
</html>

app/views/projects/_form.html.erb
<%= simple_form_for @project do |f| %>
  <%= f.input :name %>
  <%= f.association :customer, as: :radio_buttons %>
  <%= f.button :submit %>
<% end %>

app/views/projects/edit.html.erb
<h1>Edit Project </h1>
<%= render partial: 'form' %>

app/views/projects/index.html.erb
<h2>Projects</h2>

<div class="button-container">
  <% @projects.each do |project| %>
    <div class="m-top">
      <%= link_to project do %>
        Project: <%= project.name %>

      <% end %>
    </div>
  <% end %>
</div>

<div>
  <%= link_to 'Create a project', new_project_path %>
</div>

app/views/projects/new.html.erb
<h1>New Project</h1>
<%= render partial: 'form' %>

app/views/projects/show.html.erb
<h3> Project #<%= @project.id %> </h3>

<div>
  Name: <%= @project.name %>
  <br>
  Customer Id: <%= @project.customer_id %>
  <br>
  Created at <%= @project.created_at.strftime('%m/%d/%Y @ %I:%M%p') %>
</div>

<div class="button-container">
  <%= link_to "Edit", edit_project_path %>
  <%= link_to "Delete", project_path, method: :delete, data: { confirm: 'Are you sure?' } %>
</div>

app/views/task_logs/_form.html.erb
<%= simple_form_for @task_log do |f| %>
  <%= f.input :duration_minutes %>
  <%= f.association :task, label_method: :description %>
  <%= f.button :submit %>
<% end %>

app/views/task_logs/new.html.erb
<h1>New Project</h1>
<%= render partial: 'form' %>

app/views/tasks/_form.html.erb
<%= simple_form_for @task do |f| %>
  <%= f.input :description %>
  <%= f.association :project, as: :radio_buttons %>
  <%= f.button :submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit Task </h1>
<%= render partial: 'form' %>

app/views/tasks/index.html.erb
<h2>Tasks</h2>

<div class="button-container">
  <% @tasks.each do |task| %>
    <div class="m-top">
      <%= link_to task do %>
        Task: <%= task.description %>
      <% end %>
    </div>
  <% end %>
</div>

<div>
  <%= link_to 'Create a task', new_task_path %>

  <%= link_to "Log Time", new_task_log_path %>
</div>

app/views/tasks/new.html.erb
<h1>New Project</h1>
<%= render partial: 'form' %>

app/views/tasks/show.html.erb
<h3> Task #<%= @task.id %> </h3>

<div>
  Name: <%= @task.description %>
  <br>
  Project: <%= @task&.project&.name %>
  <br>
  Created at <%= @task.created_at.strftime('%m/%d/%Y @ %I:%M%p') %>
</div>

<div class="button-container">
  <%= link_to "Edit", edit_task_path %>
  <%= link_to "Delete", task_path, method: :delete, data: { confirm: 'Are you sure?' } %>

</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>